name: fleva_icons
description: A best Eva Icons package for Flutter.
version: 1.0.0
author: 'Caiubi Tech <caiubi.app@gmail.com>'
homepage: 'https://github.com/caiubitech/fleva_icons'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: FlevaIcons
      fonts:
        - asset: lib/fonts/FlevaIcons.ttf
